### ISSUE TITLE
Swizzled methods override openURL, break handleURL functionality

### ISSUE THREAD

**Issue by skicson** [localytics/localytics-cordova#30]
My app uses the Cordova `handleURL` method to import data files from email attachments.  `handleURL` gets called via a notification broadcast from `CDVAppDelegate.m`.  The localytics plugin replaces the default behavior which causes the notification to never be sent and breaks the app functionality.

I noted there were several swizzled methods which could cause similar problems.

**Comment by Mriegel** [comment]
@skicson Sorry to hear you are having trouble.  The Localytics SDK doesn't do any swizzling.  We do inject a proxy in between your `AppDelegate` for the sake of our auto-integration though.

In the past we have seen issues arise with the `handleURL` method specifically when used in conjunction with certain libraries such as Firebase. If you are integrating with Firebase, there is some documentation to help you avoid the swizzling they do that can cause issue: 
https://docs.localytics.com/dev/ios.html#integrating-with-firebase

Additionally, the Localytics SDK only injects it's proxy if you are using Automatic integration (calling `autoIntegrate` to initialize the SDK). The quickest way to get to your desired behavior may be to use Manual Integration (calling `integrate` to initialize the SDK and managing your own calls to `openSession` and `closeSession`). 

With all of that said, I'd prefer to better understand your issue so that we can make improvements if necessary.  Would you be willing to share more details of your use case, your app and your issue?

**Comment by skicson** [comment]
@Mriegel - I appreciate the comments.  I would think that the use of `MethodSwizzle` in `LocalyticsPlugin.m` would suggest that the SDK is swizzling the default Application delegate behaviors, but perhaps that's just semantics.    

In any case, debugging showed that the `localytics_swizzled_Application:handleOpenURL:));` was getting called and the CDVApplicationDelegate `handleOpenURL` method was not.  Once the localytics method was commented out, it worked as expected.

For the time being, I've reverted to an earlier version of the library since it seemed that there were some dependencies I didn't have time to figure out.

As far as use case, etc., we use localytics just for basic user information and tracking things like purchases.  Not much beyond that although we will likely add more analytics later.  We are not using firebase in this app but we are using `autoIntegrate`.

Thanks for the help.

**Comment by Mriegel** [comment]
@skicson I apologize - you're absolutely right.  My above comments apply to the native SDK and I failed to take into account the specifics of the wrapper.  I will add a ticket to our team's backlog so that we can investigate what can be done.

I'll leave this issue open and update it as I have more information for you.

**Comment by Mriegel** [comment]
This issue will be fixed as a part of the next release which will additionally include SDK 5.2.  The Localytics 5.2 SDK will be released before the end of this month and an update to Cordova will occur shortly afterwards.

**Comment by Mriegel** [comment]
@skicson SDK 5.2 has been released and is now available for your use.  I will be closing this issue as the new SDK resolves this problem.
